[platformio]
default_envs = nodemcuv2

[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_speed = 115200
monitor_filters = time
lib_deps =
    adafruit/Adafruit BME680 Library@^2.0.5
    mobizt/Firebase Arduino Client Library for ESP8266 and ESP32@^4.4.17
build_flags =
    -DCORE_DEBUG_LEVEL=3

[env:native]
platform = native
test_framework = custom
test_filter = host
test_build_src = no
